# Generated by Django 3.2.5 on 2021-07-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
